apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: 984365597202.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest
        ports:
        - containerPort: 5001
